export const tabs = {
  code: 200,
  msg: 'ok',
  data: [
    { label: '团队', name: 'team', count: 5 },
    { label: '工时', name: 'work_time', count: 5 },
    { label: '项目', name: 'project', count: 9 },
    { label: '迭代', name: 'sprint', count: 5 },
    { label: '需求', name: 'requirement', count: 12 },
    { label: '缺陷', name: 'defect', count: 14 },
    { label: '代码', name: 'repository', count: 10 },
  ],
}

export const cards = {
  code: 200,
  msg: 'ok',
  data: [
    {
      cardId: 'project-worktime-count-rank',
      category: 'project',
      creatorId: 'admin',
      description: '当前时刻各项目预计工时总量的Top5数值，点击"查看全部"可查看完整排名',
      descriptionEn: 'Project workitime count rank.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804913023,
      identifier: 'project-worktime-count-rank',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i2/O1CN01ACgl411rGDuR38xrW_!!6000000005603-2-tps-1068-576.png',
      reportCategorys: 'team,project,',
      title: '预估工时按项目排名',
      titleEn: 'Project workitem count rank',
      type: 'normal',
      width: 50,
      w: 12,
      h: 2,
    },
    {
      cardId: 'sprint-work-time-investment-rank',
      category: 'sprint',
      creatorId: 'admin',
      description: '所选时间区间内各成员的登记工时Top5数值，点击"查看全部"可查看完整排名',
      descriptionEn: 'Work time investment rank.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804913016,
      identifier: 'sprint-work-time-investment-rank',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i2/O1CN01WdqqQh1GreUoztAKY_!!6000000000676-2-tps-1068-576.png',
      reportCategorys: 'sprint,',
      title: '迭代工时排名',
      titleEn: 'Work time investment rank',
      type: 'normal',
      width: 50,
      w: 12,
      h: 2,
    },
    {
      cardId: 'team-workitem-done-rank',
      category: 'team',
      creatorId: 'admin',
      description: '当前时刻，指派给各成员的已完成和总的工作项数量。',
      descriptionEn: 'Team workitem done rank',
      gmtCreate: 1616060562800,
      gmtModified: 1655804913008,
      identifier: 'team-workitem-done-rank',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i1/O1CN01Is5XoW1O054uXZkDy_!!6000000001642-2-tps-1068-576.png',
      reportCategorys: 'personal,team,project,sprint,single_project,',
      title: '工作项排名',
      titleEn: 'Team workitem done rank',
      type: 'normal',
      width: 50,
      w: 12,
      h: 2,
    },
    {
      cardId: 'work-time-burn-down',
      category: 'work_time',
      creatorId: 'admin',
      description: '从迭代计划开始到计划结束时间区间内，理想情况下的每日工时余量曲线和实际的工时余量曲线。',
      descriptionEn: 'Work time burn down',
      gmtCreate: 1616060562800,
      gmtModified: 1655804913001,
      identifier: 'work-time-burn-down',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i4/O1CN012tuwt81JkjLDgJfEC_!!6000000001067-2-tps-1068-576.png',
      reportCategorys: 'sprint,',
      title: '工时燃尽图',
      titleEn: 'Work time burn down',
      type: 'normal',
      width: 50,
      w: 6,
      h: 2,
    },
    {
      cardId: 'sprint-work-time-summary',
      category: 'sprint',
      creatorId: 'admin',
      description: '当前时刻迭代的工时容量、预估工时、登记工时及到当前时刻预估使用工时与实际登记工时的偏差量。',
      descriptionEn: 'Sprint work time summary',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912993,
      identifier: 'sprint-work-time-summary',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i1/O1CN01f47EcM1icMUkRr55B_!!6000000004433-2-tps-1068-576.png',
      reportCategorys: 'sprint,',
      title: '迭代工时概览',
      titleEn: 'Sprint work time summary',
      type: 'normal',
      width: 50,
      w: 6,
      h: 1,
    },
    {
      cardId: 'project-workitem-done-count',
      category: 'sprint',
      creatorId: 'admin',
      description: '当前时刻迭代包含的工作项数量和完成情况。',
      descriptionEn: 'Project workitem done count',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912986,
      identifier: 'project-workitem-done-count',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i1/O1CN01Q7DVOE1L9kanze9zv_!!6000000001257-2-tps-1068-576.png',
      reportCategorys: 'sprint,',
      title: '迭代工作项概览',
      titleEn: 'Project workitem done count',
      type: 'normal',
      width: 50,
      w: 6,
      h: 1,
    },
    {
      cardId: 'defect-new-workitem-tendency',
      category: 'defect',
      creatorId: 'admin',
      description:
        '所选时间区间内，各个项目的新增缺陷数量曲线，每次最多展示10个项目的变化趋势。横坐标是日期，纵坐标是数量，一条曲线代表某项目在该时间内，新发现缺陷数量的变化趋势。本图可反映各项目的新增缺陷数量的变化趋势，期待数量少且持续输入，同时也可进行各项目间对比。',
      descriptionEn: 'New defect workitem tendency',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912978,
      identifier: 'defect-new-workitem-tendency',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i3/O1CN01VTtdAy1foJzLcJKpO_!!6000000004053-2-tps-1068-576.png',
      reportCategorys: 'team,project,personal,',
      title: '新增缺陷趋势',
      titleEn: 'New defect workitem tendency',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'requirement-new-workitem-tendency',
      category: 'requirement',
      creatorId: 'admin',
      description:
        '所选时间区间内，各个项目的新增需求数量曲线，每次最多展示10个项目的变化趋势。横坐标是日期，纵坐标是数量，一条曲线代表某项目在该时间内，新增需求数量的变化趋势。本图可反映各项目的新增需求数量的变化趋势，期待新增需求持续输入且数量相对稳定，同时也可进行各项目间对比。',
      descriptionEn: 'New requirement workitem tendency',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912971,
      identifier: 'requirement-new-workitem-tendency',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i3/O1CN01WHE5sO1KLpPt9RJG4_!!6000000001148-2-tps-1068-576.png',
      reportCategorys: 'team,project,personal,',
      title: '新增需求趋势',
      titleEn: 'New requirement workitem tendency',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'defect-duration-accumulation-with-stage',
      category: 'defect',
      creatorId: 'admin',
      description:
        '所选时间区间内，按周查看缺陷在各阶段平均停留时长分布的面积图。通过各阶段曲线的趋势看到修复周期的趋势，并能反映对缺陷的响应能力情况，周期越短代表响应能力越快。通过看各阶段的面积占比大小，可反映需求在哪个阶段停留时间的长度，针对停留时间特别长的阶段可做进一步分析。',
      descriptionEn: 'Defect fixed time accumulation with stage',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912963,
      identifier: 'defect-duration-accumulation-with-stage',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i3/O1CN01USqjA926Lv3NhKahn_!!6000000007646-2-tps-1068-576.png',
      reportCategorys: 'team,project,personal,sprint,',
      title: '修复缺陷按阶段停留累积',
      titleEn: 'Defect fixed time accumulation with stage',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'requirement-duration-accumulation-with-stage',
      category: 'requirement',
      creatorId: 'admin',
      description:
        '所选时间区间内，按周查看需求在各阶段平均停留时长分布的面积图。通过发布阶段曲线的趋势看到交付周期的趋势，并能反映对需求的响应能力情况，周期越短代表响应能力越快。通过看各阶段的面积占比大小，可反映需求在哪个阶段停留时间的长度，针对停留时间特别长的阶段可做进一步分析。',
      descriptionEn: 'Requirement release time accumulation with stage',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912956,
      identifier: 'requirement-duration-accumulation-with-stage',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i1/O1CN01wqs70s1o5HaIadE8B_!!6000000005173-2-tps-1068-576.png',
      reportCategorys: 'team,project,personal,sprint,',
      title: '交付需求按阶段停留累积',
      titleEn: 'Requirement release time accumulation with stage',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'defect-burn-up',
      category: 'defect',
      creatorId: 'admin',
      description:
        '所选时间区间内，已修复缺陷和缺陷总量的累积趋势图，横坐标是日期，纵坐标是缺陷的数量。"完成曲线"和"全部曲线"之间的距离代表剩余需修复的缺陷数，完成曲线的斜率代表缺陷的修复速度，两条曲线的交叉点所对应的日期为缺陷全部修复完成的时间点。',
      descriptionEn: 'Defect burn up',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912949,
      identifier: 'defect-burn-up',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i2/O1CN01ctEqs21TfMr8JHf4V_!!6000000002409-2-tps-1068-576.png',
      reportCategorys: 'team,project,personal,',
      title: '缺陷燃起图',
      titleEn: 'Defect burn up',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'requirement-burn-up',
      category: 'requirement',
      creatorId: 'admin',
      description:
        '所选时间区间内，已完成需求和需求总量的累积趋势图，横坐标是日期，纵坐标是需求的数量。"完成曲线"和"全部曲线"之间的距离代表剩余需交付的需求量，完成曲线的斜率代表需求的交付速度，两条曲线的交叉点所对应的日期为需求全部完成时间点',
      descriptionEn: 'Requirement burn up',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912941,
      identifier: 'requirement-burn-up',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i2/O1CN01NRuN9z1CKRHzlnccQ_!!6000000000062-2-tps-1068-576.png',
      reportCategorys: 'team,project,personal,',
      title: '需求燃起图',
      titleEn: 'Requirement burn up',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'project-accumulation',
      category: 'project',
      creatorId: 'admin',
      description: '所选时间区间内，待完成的工作项待处理、处理中、已完成数量累积变化曲线',
      descriptionEn: 'Project accumulation',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912934,
      identifier: 'project-accumulation',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i4/O1CN01Lp78gC22LgNaKbk9g_!!6000000007104-2-tps-1068-576.png',
      reportCategorys: 'single_project,',
      title: '工作项累积流图',
      titleEn: 'Project accumulation',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'requirement-done-summary',
      category: 'requirement',
      config:
        '{"tableColumnConfigs":[{"name":"名称","nameI18n":"subject","path":"/subject","style":"workitem-title","link":"/url","type":"/type"},{"name":"状态","nameI18n":"status","path":"/stage, /status","style":"color-background-text"},{"name":"优先级","nameI18n":"priority","path":"/priority","style":"color-circle-text","sortKey":"priority"},{"name":"负责人","nameI18n":"assignedToName","path":"/assignedToName, /assignedToAvatarUrl","style":"avatar"},{"name":"项目名","nameI18n":"projectName","path":"/projectName","style":"text"},{"name":"创建时间","nameI18n":"gmtCreate","path":"/gmtCreate","style":"date","format":"YYYY.MM.DD","sortKey":"gmtCreate"},{"name":"完成时间","path":"/gmtClosed","color":"date","format":"YYYY.MM.DD","sortKey":"gmtClosed"}]}',
      creatorId: 'admin',
      description:
        '所选时间区间内完成的需求数量、从进入排期到完成的平均时长、平均每日完成需求数量，以及相比上个时间周期的变化率',
      descriptionEn: 'Requirement done summary',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912926,
      identifier: 'requirement-done-summary',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i2/O1CN01S8uU3B1CzevxMVLw1_!!6000000000152-2-tps-1068-576.png',
      reportCategorys: 'personal,team,project,sprint,single_project,',
      title: '需求交付效率概览',
      titleEn: 'Requirement done summary',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'defect-new-workitem-summary',
      category: 'defect',
      config:
        '{"tableColumnConfigs":[{"name":"名称","nameI18n":"subject","path":"/subject","style":"workitem-title","link":"/url","type":"/type"},{"name":"状态","nameI18n":"status","path":"/stage, /status","style":"color-background-text"},{"name":"优先级","nameI18n":"priority","path":"/priority","style":"color-circle-text","sortKey":"priority"},{"name":"负责人","nameI18n":"assignedToName","path":"/assignedToName, /assignedToAvatarUrl","style":"avatar"},{"name":"项目名","nameI18n":"projectName","path":"/projectName","style":"text"},{"name":"创建时间","nameI18n":"gmtCreate","path":"/gmtCreate","style":"date","format":"YYYY.MM.DD","sortKey":"gmtCreate"},{"name":"计划完成时间","path":"/expectedWorkTime","style":"date","format":"YYYY.MM.DD","sortKey":"expectedWorkTime"},{"name":"再次打开次数","path":"/reopenNum","color":"text","sortKey":"reopenNum"}]}',
      creatorId: 'admin',
      description: '所选时间区间内新增的缺陷数量，以及这些缺陷当前的状态分布',
      descriptionEn: 'New defect workitem summary.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912919,
      identifier: 'defect-new-workitem-summary',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i2/O1CN01RetPp71dHE6y4NS8E_!!6000000003710-2-tps-1068-576.png',
      reportCategorys: 'personal,team,project,sprint,single_project,',
      title: '新增缺陷概览',
      titleEn: 'New defect workitem summary',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'defect-accumulation',
      category: 'defect',
      creatorId: 'admin',
      description: '所选时间区间内每日处于待处理、处理中、已完成阶段的缺陷数量变化曲线',
      descriptionEn: 'Defect accumulation.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912911,
      identifier: 'defect-accumulation',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i4/O1CN01PhGn3h1VqTfYMQ2wN_!!6000000002704-2-tps-1068-576.png',
      reportCategorys: 'personal,team,project,sprint,single_project,',
      title: '缺陷累积流图',
      titleEn: 'Defect accumulation',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'requirement-new-workitem-summary',
      category: 'requirement',
      config:
        '{"tableColumnConfigs":[{"name":"名称","nameI18n":"subject","path":"/subject","style":"workitem-title","link":"/url","type":"/type"},{"name":"状态","nameI18n":"status","path":"/stage, /status","style":"color-background-text"},{"name":"优先级","nameI18n":"priority","path":"/priority","style":"color-circle-text","sortKey":"priority"},{"name":"负责人","nameI18n":"assignedToName","path":"/assignedToName, /assignedToAvatarUrl","style":"avatar"},{"name":"项目名","nameI18n":"projectName","path":"/projectName","style":"text"},{"name":"创建时间","nameI18n":"gmtCreate","path":"/gmtCreate","style":"date","format":"YYYY.MM.DD","sortKey":"gmtCreate"},{"name":"计划完成时间","nameI18n":"expectedWorkTime","path":"/expectedWorkTime","style":"date","format":"YYYY.MM.DD","sortKey":"expectedWorkTime"},{"name":"逾期时长","nameI18n":"dueDuration","path":"/dueDuration","style":"color-time-text","sortKey":"dueDuration"}]}',
      creatorId: 'admin',
      description: '所选时间区间内新增的需求数量，以及这些需求当前的状态分布',
      descriptionEn: 'New Requirement workitem summary.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912904,
      identifier: 'requirement-new-workitem-summary',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i3/O1CN01YYNpBc1pVDbDlilvs_!!6000000005365-2-tps-1068-576.png',
      reportCategorys: 'personal,team,project,sprint,single_project,',
      title: '新增需求概览',
      titleEn: 'New Requirement workitem summary',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'requirement-accumulation',
      category: 'requirement',
      creatorId: 'admin',
      description: '所选时间区间内每日处于待处理、处理中、已完成阶段的需求数量变化曲线',
      descriptionEn: 'Requirement accumulation.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912896,
      identifier: 'requirement-accumulation',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i1/O1CN011qs4881E7H8Vbnu4N_!!6000000000304-2-tps-1068-576.png',
      reportCategorys: 'personal,team,project,sprint,single_project,',
      title: '需求累积流图',
      titleEn: 'Requirement accumulation',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'requirement-classification-distribution-remained',
      category: 'requirement',
      creatorId: 'admin',
      description: '当前时刻尚未完成的需求按优先级、状态、阶段的分布占比',
      descriptionEn: 'Requirement classification distribution remained.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912889,
      identifier: 'requirement-classification-distribution-remained',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i4/O1CN01mI2cc91SMl7ZnOAhQ_!!6000000002233-2-tps-1068-576.png',
      reportCategorys: 'personal,team,project,sprint,single_project,',
      title: '存量需求占比',
      titleEn: 'Requirement classification distribution remained',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'project-new-workitem-summary',
      category: 'project',
      config:
        '{"tableColumnConfigs":[{"name":"名称","nameI18n":"subject","path":"/subject","style":"workitem-title","link":"/url","type":"/type"},{"name":"状态","nameI18n":"status","path":"/stage, /status","style":"color-background-text"},{"name":"优先级","nameI18n":"priority","path":"/priority","style":"color-circle-text","sortKey":"priority"},{"name":"负责人","nameI18n":"assignedToName","path":"/assignedToName, /assignedToAvatarUrl","style":"avatar"},{"name":"项目名","nameI18n":"projectName","path":"/projectName","style":"text"},{"name":"创建时间","nameI18n":"gmtCreate","path":"/gmtCreate","style":"date","format":"YYYY.MM.DD","sortKey":"gmtCreate"},{"name":"计划完成时间","nameI18n":"expectedWorkTime","path":"/expectedWorkTime","style":"date","format":"YYYY.MM.DD","sortKey":"expectedWorkTime"},{"name":"逾期时长","nameI18n":"dueDuration","path":"/dueDuration","style":"color-time-text","sortKey":"dueDuration"}]}',
      creatorId: 'admin',
      description: '所选时间区间内新增的工作项数量，以及这些工作项当前的状态分布',
      descriptionEn: 'New project workitem summary.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912874,
      identifier: 'project-new-workitem-summary',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i4/O1CN018D85gF1rexFeTRvTb_!!6000000005657-2-tps-1068-576.png',
      reportCategorys: 'personal,team,project,sprint,single_project,',
      title: '新增工作项概览',
      titleEn: 'New project workitem summary',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'work-time-distribution',
      category: 'work_time',
      creatorId: 'admin',
      description: '所选时间区间内每日登记工时人数、有工时登记的工作项数、登记的总工时量',
      descriptionEn: 'Work time distribution.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912867,
      identifier: 'work-time-distribution',
      minWidth: 100,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i1/O1CN01Z6WZWn1aIeV82Ba4C_!!6000000003307-2-tps-1068-576.png',
      reportCategorys: 'team,personal,project,',
      title: '工时时间分布',
      titleEn: 'Work time distribution',
      type: 'normal',
      width: 100,
    },
    {
      cardId: 'work-time-classification',
      category: 'work_time',
      creatorId: 'admin',
      description: '所选时间区间内登记工时按类别的分布情况',
      descriptionEn: 'work time classification.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912859,
      identifier: 'work-time-classification',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i1/O1CN01g8Kvtw1RqF0UMczRk_!!6000000002162-2-tps-1068-576.png',
      reportCategorys: 'team,project,',
      title: '工时按类别分布',
      titleEn: 'work time classification',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'work-time-investment-rank',
      category: 'work_time',
      creatorId: 'admin',
      description: '所选时间区间内各成员的登记工时Top5数值，点击"查看全部"可查看完整排名',
      descriptionEn: 'Work time investment rank.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912852,
      identifier: 'work-time-investment-rank',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i3/O1CN01YnJbPT1lofy8b1vqK_!!6000000004866-2-tps-1068-576.png',
      reportCategorys: 'team,project,',
      title: '工时投入排名',
      titleEn: 'Work time investment rank',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'work-time-summary',
      category: 'work_time',
      creatorId: 'admin',
      description:
        '所选时间区间内的预估工时总量、已登记工时总量、尚未使用的预估剩余工时、到当前时刻预估使用工时与实际登记工时的偏差量、实/应登记人数、实/应登记工作项',
      descriptionEn: 'Work time summary.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912845,
      identifier: 'work-time-summary',
      minWidth: 100,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i2/O1CN012AV503292dC2dUVqa_!!6000000008010-2-tps-1068-576.png',
      reportCategorys: 'team,personal,project,',
      title: '工时概览',
      titleEn: 'Work time summary',
      type: 'normal',
      width: 100,
    },
    {
      cardId: 'code-commit-distribution',
      category: 'repository',
      creatorId: 'admin',
      description: '开发者在近一年内每天的代码提交次数分布，颜色越深表示在该区间的提交次数越多',
      descriptionEn: 'Code commit distribution.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912837,
      identifier: 'code-commit-distribution',
      minWidth: 100,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i3/O1CN01p8dGBh1sRxd1jbqMt_!!6000000005764-2-tps-1068-576.png',
      reportCategorys: 'personal,',
      title: '代码提交量',
      titleEn: 'Code commit distribution',
      type: 'normal',
      width: 100,
    },
    {
      cardId: 'project-workitem-done-distribution',
      category: 'project',
      config:
        '{"tableColumnConfigs":[{"name":"名称","nameI18n":"subject","path":"/subject","style":"workitem-title","link":"/url","type":"/type"},{"name":"状态","nameI18n":"status","path":"/stage, /status","style":"color-background-text"},{"name":"优先级","nameI18n":"priority","path":"/priority","style":"color-circle-text","sortKey":"priority"},{"name":"负责人","nameI18n":"assignedToName","path":"/assignedToName, /assignedToAvatarUrl","style":"avatar"},{"name":"项目名","nameI18n":"projectName","path":"/projectName","style":"text"},{"name":"创建时间","nameI18n":"gmtCreate","path":"/gmtCreate","style":"date","format":"YYYY.MM.DD","sortKey":"gmtCreate"},{"name":"计划完成时间","nameI18n":"expectedWorkTime","path":"/expectedWorkTime","style":"date","format":"YYYY.MM.DD","sortKey":"expectedWorkTime"},{"name":"逾期时长","nameI18n":"dueDuration","path":"/dueDuration","style":"color-time-text","sortKey":"dueDuration"}]}',
      creatorId: 'admin',
      description: '所选时间区间内完成的工作项总数及其类型分布，可下钻查看完成的工作项列表',
      descriptionEn: 'Project workitem done distribution.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912830,
      identifier: 'project-workitem-done-distribution',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i4/O1CN01HOisQb1T717bzaJ5m_!!6000000002334-2-tps-1068-576.png',
      reportCategorys: 'personal,sprint,single_project,',
      title: '完成工作项占比',
      titleEn: 'Project workitem done distribution',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'defect-done-summary',
      category: 'defect',
      config:
        '{"tableColumnConfigs":[{"name":"名称","nameI18n":"subject","path":"/subject","style":"workitem-title","link":"/url","type":"/type"},{"name":"状态","nameI18n":"status","path":"/stage, /status","style":"color-background-text"},{"name":"优先级","nameI18n":"priority","path":"/priority","style":"color-circle-text","sortKey":"priority"},{"name":"负责人","nameI18n":"assignedToName","path":"/assignedToName, /assignedToAvatarUrl","style":"avatar"},{"name":"项目名","nameI18n":"projectName","path":"/projectName","style":"text"},{"name":"创建时间","nameI18n":"gmtCreate","path":"/gmtCreate","style":"date","format":"YYYY.MM.DD","sortKey":"gmtCreate"},{"name":"完成时间","path":"/gmtClosed","color":"date","format":"YYYY.MM.DD","sortKey":"gmtClosed"}]}',
      creatorId: 'admin',
      description:
        '所选时间区间内完成的缺陷数量、从进入排期到完成的平均时长、平均每日完成的缺陷数量，以及相比上个时间周期的变化率',
      descriptionEn: 'Defect done summary.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912822,
      identifier: 'defect-done-summary',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i1/O1CN01zCCH1c1XdlwJ7PdE1_!!6000000002947-2-tps-1068-576.png',
      reportCategorys: 'project,sprint,single_project,',
      title: '缺陷修复效率概览',
      titleEn: 'Defect done summary',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'project-progress-detail',
      category: 'project',
      creatorId: 'admin',
      description:
        '各项目当前时刻尚未完成的工作项数、已超过计划完成时间的工作项数、所选时间区间内的平均交付周期和新增完成工作项比例',
      descriptionEn: 'Project progress detail.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912815,
      identifier: 'project-progress-detail',
      minWidth: 100,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i2/O1CN01QYl5re1nvfGQAwJgS_!!6000000005152-2-tps-1068-576.png',
      reportCategorys: 'project,',
      title: '项目进展',
      titleEn: 'Project progress detail',
      type: 'normal',
      width: 100,
    },
    {
      cardId: 'project-investment-rank',
      category: 'project',
      creatorId: 'admin',
      description: '当前时刻各项目的成员人数或在所选时间区间内实际工时填报量的Top5数值，点击"查看全部"可查看完整排名',
      descriptionEn: 'Project investment rank.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912807,
      identifier: 'project-investment-rank',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i1/O1CN01tTMzTz1BvFTjcfGu8_!!6000000000007-2-tps-1068-576.png',
      reportCategorys: 'project,',
      title: '项目投入人力排名',
      titleEn: 'Project investment rank',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'sprint-progress',
      category: 'sprint',
      creatorId: 'admin',
      description: '各项目中进行中、未开始、已完成的迭代的状态、进展、登记/规划工时及已超期事项等',
      descriptionEn: 'Sprint progress.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912800,
      identifier: 'sprint-progress',
      minWidth: 100,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i4/O1CN01cCz2JM1cPBP4GueX0_!!6000000003592-2-tps-1068-576.png',
      reportCategorys: 'project,personal,',
      title: '迭代进展',
      titleEn: 'Sprint progress',
      type: 'normal',
      width: 100,
    },
    {
      cardId: 'project-workitem-summary',
      category: 'project',
      config:
        '{"tableColumnConfigs":[{"name":"名称","nameI18n":"subject","path":"/subject","style":"workitem-title","link":"/url","type":"/type"},{"name":"状态","nameI18n":"status","path":"/stage, /status","style":"color-background-text"},{"name":"优先级","nameI18n":"priority","path":"/priority","style":"color-circle-text","sortKey":"priority"},{"name":"负责人","nameI18n":"assignedToName","path":"/assignedToName, /assignedToAvatarUrl","style":"avatar"},{"name":"项目名","nameI18n":"projectName","path":"/projectName","style":"text"},{"name":"创建时间","nameI18n":"gmtCreate","path":"/gmtCreate","style":"date","format":"YYYY.MM.DD","sortKey":"gmtCreate"},{"name":"计划完成时间","nameI18n":"expectedWorkTime","path":"/expectedWorkTime","style":"date","format":"YYYY.MM.DD","sortKey":"expectedWorkTime"},{"name":"逾期时长","nameI18n":"dueDuration","path":"/dueDuration","style":"color-time-text","sortKey":"dueDuration"}]}',
      creatorId: 'admin',
      description:
        '当前时刻尚未开始、正在进行、尚未设置计划开始/完成时间、和已超过计划完成时间的工作项数量，可下钻查看列表',
      descriptionEn: 'Project workitem summary.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912792,
      identifier: 'project-workitem-summary',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i3/O1CN01jDnShy1zKMMl1LDqo_!!6000000006695-2-tps-1068-576.png',
      reportCategorys: 'project,personal,sprint,single_project,',
      title: '工作项现状概览',
      titleEn: 'Project workitem summary',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'project-workitem-count-rank',
      category: 'project',
      creatorId: 'admin',
      description: '当前时刻各项目尚未完成的工作项数量 Top5 数值，点击"查看全部"可查看完整排名',
      descriptionEn: 'Project workitem count rank.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912785,
      identifier: 'project-workitem-count-rank',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i3/O1CN01IdXd821tNDBRDx6Vl_!!6000000005889-2-tps-1068-576.png',
      reportCategorys: 'team,project,',
      title: '存量工作项按项目排名',
      titleEn: 'Project workitem count rank',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'project-workitem-proportion',
      category: 'project',
      config:
        '{"tableColumnConfigs":[{"name":"名称","nameI18n":"subject","path":"/subject","style":"workitem-title","link":"/url","type":"/type"},{"name":"状态","nameI18n":"status","path":"/stage, /status","style":"color-background-text"},{"name":"优先级","nameI18n":"priority","path":"/priority","style":"color-circle-text","sortKey":"priority"},{"name":"负责人","nameI18n":"assignedToName","path":"/assignedToName, /assignedToAvatarUrl","style":"avatar"},{"name":"项目名","nameI18n":"projectName","path":"/projectName","style":"text"},{"name":"创建时间","nameI18n":"gmtCreate","path":"/gmtCreate","style":"date","format":"YYYY.MM.DD","sortKey":"gmtCreate"},{"name":"计划完成时间","nameI18n":"expectedWorkTime","path":"/expectedWorkTime","style":"date","format":"YYYY.MM.DD","sortKey":"expectedWorkTime"}]}',
      creatorId: 'admin',
      description: '当前时刻尚未完成的工作项总数及其类型分布，可下钻查看未完成的工作项列表',
      descriptionEn: 'Project workitem proportion.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912777,
      identifier: 'project-workitem-proportion',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i1/O1CN01kjYajD1swBlnuVi0J_!!6000000005830-2-tps-1068-576.png',
      reportCategorys: 'project,team,sprint,single_project,',
      title: '存量工作项占比',
      titleEn: 'Project workitem proportion',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'team-member-work-detail',
      category: 'team',
      creatorId: 'admin',
      description:
        '各成员当前时刻尚未完成的工作项数、尚未完成的缺陷数、已超过计划完成时间的工作项数，以及在所选时间区间内新增和完成工作项数量比例、从排期到完成的平均耗时、代码提交次数、代码增删行数',
      descriptionEn: 'Team workitem.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912770,
      identifier: 'team-member-work-detail',
      minWidth: 100,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i2/O1CN01gU0a9t26Thl49jY4A_!!6000000007663-2-tps-1068-576.png',
      reportCategorys: 'team,',
      title: '成员工作',
      titleEn: 'Team workitem',
      type: 'normal',
      width: 100,
    },
    {
      cardId: 'team-workitem-count-rank',
      category: 'team',
      creatorId: 'admin',
      description: '当前时刻各成员待完成的工作项数量Top5数值，点击"查看全部"可查看完整排名',
      descriptionEn: 'Team workitem count rank.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912754,
      identifier: 'team-workitem-count-rank',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i1/O1CN01UWDTGj1OaimjK8BgU_!!6000000001722-2-tps-1068-576.png',
      reportCategorys: 'team,sprint,project,single_project,sprint,',
      title: '存量工作项按成员排名',
      titleEn: 'Team workitem count rank',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'team-investment',
      category: 'team',
      creatorId: 'admin',
      description: '所选时间区间内各相关项目的完成工作项数量和登记工时量占比',
      descriptionEn: 'Team investment.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912747,
      identifier: 'team-investment',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i1/O1CN01dZiu161IlMET8PiGU_!!6000000000933-2-tps-1068-576.png',
      reportCategorys: 'team,',
      title: '兵力投入',
      titleEn: 'Team investment',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'team-summary',
      category: 'team',
      creatorId: 'admin',
      description: '当前时刻所选团队包含的成员数、参与项目总数、参与代码库总数',
      descriptionEn: 'Team summary.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912740,
      identifier: 'team-summary',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i2/O1CN01Of3O7q1ikbapOHdEB_!!6000000004451-2-tps-1068-576.png',
      reportCategorys: 'team,',
      title: '团队概览',
      titleEn: 'Team summary',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'defect-project-remained-tendency',
      category: 'defect',
      creatorId: 'admin',
      description: '所选时间区间各项目尚未完成缺陷的数量曲线，每次最多展示10个项目的变化趋势',
      descriptionEn: 'Defect member remained rank.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912732,
      identifier: 'defect-project-remained-tendency',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i1/O1CN01GL34oU1hduBtpvru3_!!6000000004301-2-tps-1068-576.png',
      reportCategorys: 'project,team,',
      title: '存量缺陷趋势',
      titleEn: 'Defect member remained rank',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'requirement-project-remained-tendency',
      category: 'requirement',
      creatorId: 'admin',
      description: '所选时间区间项目尚未完成需求的数量曲线，每次最多展示10个项目的变化趋势',
      descriptionEn: 'Requirement project remained tendency.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912725,
      identifier: 'requirement-project-remained-tendency',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i1/O1CN01DarAsb1LGA70eV8qW_!!6000000001271-2-tps-1068-576.png',
      reportCategorys: 'project,team,',
      title: '存量需求趋势',
      titleEn: 'Requirement project remained tendency',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'defect-member-remained-rank',
      category: 'defect',
      creatorId: 'admin',
      description: '当前时刻各成员尚未完成的缺陷数量Top5数值，点击"查看全部"可查看完整排名',
      descriptionEn: 'Defect member remained rank.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912717,
      identifier: 'defect-member-remained-rank',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i2/O1CN01haWRuj1Pnpgcp6Nzj_!!6000000001886-2-tps-1068-576.png',
      reportCategorys: 'project,sprint,single_project,team,',
      title: '存量缺陷按成员排名',
      titleEn: 'Defect member remained rank',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'defect-classification-distribution-remained',
      category: 'defect',
      creatorId: 'admin',
      description: '当前时刻尚未完成的缺陷按严重程度、优先级、状态、阶段的分布占比',
      descriptionEn: 'Defect remained classification distribution.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912710,
      identifier: 'defect-classification-distribution-remained',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i2/O1CN01X7Vnhm1Z7N7rx9pR2_!!6000000003147-2-tps-1068-576.png',
      reportCategorys: 'project,sprint,single_project,',
      title: '存量缺陷占比',
      titleEn: 'Defect remained classification distribution',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'defect-project-remained-rank',
      category: 'defect',
      creatorId: 'admin',
      description: '当前时刻各项目尚未完成的缺陷数量Top5数值，点击"查看全部"可查看完整排名',
      descriptionEn: 'Defect project remained rank.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912703,
      identifier: 'defect-project-remained-rank',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i3/O1CN016RDzL31rfs2lRiQLz_!!6000000005659-2-tps-1068-576.png',
      reportCategorys: 'project,',
      title: '存量缺陷按项目排名',
      titleEn: 'Defect project remained rank',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'code-repository-statistics',
      category: 'repository',
      creatorId: 'admin',
      description: '各代码代码库当前时刻代码行数、安全问题数，以及在所选时间区间内的提交次数、评审率、增减代码行数',
      descriptionEn: 'Code repository statistics.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912695,
      identifier: 'code-repository-statistics',
      minWidth: 100,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i1/O1CN014peCKk1zHbzOnibmf_!!6000000006689-2-tps-1068-576.png',
      reportCategorys: 'repository,',
      title: '代码库统计',
      titleEn: 'Code repository statistics',
      type: 'normal',
      width: 100,
    },
    {
      cardId: 'code-issue-rank',
      category: 'repository',
      creatorId: 'admin',
      description: '当前时刻按代码库或开发者的存量安全问题数量Top5数值，点击"查看全部"可查看完整排名',
      descriptionEn: 'Code issue rank.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912688,
      identifier: 'code-issue-rank',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i1/O1CN01M5lbJs1eKGLqt2BdE_!!6000000003852-2-tps-1068-576.png',
      reportCategorys: 'repository,team,',
      title: '代码安全问题排名',
      titleEn: 'Code issue rank',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'code-issue-tendency',
      category: 'repository',
      creatorId: 'admin',
      description: '所选时间区间内已选代码库安全问题的数量曲线，每次最多展示10个代码库的变化趋势',
      descriptionEn: 'Code issue tendency.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912681,
      identifier: 'code-issue-tendency',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i2/O1CN01eKFOe71VauCNPrp3F_!!6000000002670-2-tps-1068-576.png',
      reportCategorys: 'repository,',
      title: '代码库安全问题趋势',
      titleEn: 'Code issue tendency',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'code-commit-rank',
      category: 'repository',
      creatorId: 'admin',
      description: '所选时间区间内按代码库或开发者的代码提交次数Top5数值，点击"查看全部"可查看完整排名',
      descriptionEn: 'Code commit rank.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912673,
      identifier: 'code-commit-rank',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i1/O1CN010tBgVb1dZXx5tzSwA_!!6000000003750-2-tps-1068-576.png',
      reportCategorys: 'repository,team,',
      title: '代码提交次数排名',
      titleEn: 'Code commit rank',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'code-commit-detail-rank',
      category: 'repository',
      creatorId: 'admin',
      description: '所选时间区间内按代码库或开发者的代码行增减总量Top5数值，点击"查看全部"可查看完整排名',
      descriptionEn: 'Code commit detail rank.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912666,
      identifier: 'code-commit-detail-rank',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i4/O1CN017hXQvi1Rs4aKQ1ygn_!!6000000002166-2-tps-1068-576.png',
      reportCategorys: 'repository,team,',
      title: '代码变更量排名',
      titleEn: 'Code commit detail rank',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'code-commit-tendency',
      category: 'repository',
      creatorId: 'admin',
      description: '所选时间区间内每日新增和删除的代码行数',
      descriptionEn: 'Code commit tendency.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912658,
      identifier: 'code-commit-tendency',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i2/O1CN012vYxdk1O9hMfL2uS4_!!6000000001663-2-tps-1068-576.png',
      reportCategorys: 'repository,',
      title: '代码变更趋势',
      titleEn: 'Code commit tendency',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'code-hourly-commit-distribution',
      category: 'repository',
      creatorId: 'admin',
      description: '所选时间区间内每日各时段的代码提交次数分布，颜色越深表示在该区间的提交次数越多',
      descriptionEn: 'Code hourly commit distribution.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912651,
      identifier: 'code-hourly-commit-distribution',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i1/O1CN01OwQaVc1FMg2m1QVNA_!!6000000000473-2-tps-1068-576.png',
      reportCategorys: 'repository,',
      title: '代码提交时段分布',
      titleEn: 'Code hourly commit distribution',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'code-progress-summary',
      category: 'repository',
      creatorId: 'admin',
      description: '所选时间区间内的代码提交次数和新增、删除代码行数',
      descriptionEn: 'Code progress summary.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912643,
      identifier: 'code-progress-summary',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i3/O1CN01T0pmW728QcJt5UaxZ_!!6000000007927-2-tps-1068-576.png',
      reportCategorys: 'repository,',
      title: '代码变更概览',
      titleEn: 'Code progress summary',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'code-summary',
      category: 'repository',
      creatorId: 'admin',
      description: '当前时刻已选代码库的代码行总量和安全问题总数',
      descriptionEn: 'Code summary.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912636,
      identifier: 'code-summary',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i3/O1CN01SReuat26E8IEDBzW9_!!6000000007629-2-tps-1068-576.png',
      reportCategorys: 'repository,',
      title: '代码库概览',
      titleEn: 'Code summary',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'defect-fixed-cycle-distribution',
      category: 'defect',
      creatorId: 'admin',
      description: '所选时间区间内完成的缺陷，按关闭日期排列，并分别统计每日修复缺陷从排期到完成的耗时时长分布',
      descriptionEn: 'Defects under the project to be processed, completed, new trends.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912629,
      identifier: 'defect-fixed-cycle-distribution',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i3/O1CN01l9aLNB1GNsjIWKO7t_!!6000000000611-2-tps-1068-576.png',
      reportCategorys: 'project,sprint,single_project,',
      title: '缺陷修复速率',
      titleEn: 'Defect fixed cycle distribution',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'requirement-release-cycle-distribution',
      category: 'requirement',
      creatorId: 'admin',
      description: '所选时间区间内完成的需求，按完成日期排列，并分别统计每日完成需求从排期到完成的耗时时长分布',
      descriptionEn: 'Defects under the project to be processed, completed, new trends.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912621,
      identifier: 'requirement-release-cycle-distribution',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i4/O1CN013L6xfJ2A8sEd35kDK_!!6000000008159-2-tps-1068-576.png',
      reportCategorys: 'project,sprint,single_project,',
      title: '需求交付速率',
      titleEn: 'Requirement release cycle distribution',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'defect-fixed-distribution',
      category: 'defect',
      creatorId: 'admin',
      description:
        '所选时间区间内完成的缺陷，按完成日期排列，横坐标为时间，纵坐标为缺陷创建到修复的周期（天）。其中圆点表示一个已修复的缺陷，折线表示需求修复缺陷的滚动均值，红色阴影区域表示滚动标准差，横虚线表示所选时间区间内，缺陷修复周期的平均值',
      descriptionEn: 'Defects under the project to be processed, completed, new trends.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912613,
      identifier: 'defect-fixed-distribution',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i3/O1CN01l2mQI61CJWUnh3PCW_!!6000000000060-2-tps-1068-576.png',
      reportCategorys: 'project,team,sprint,single_project,',
      title: '缺陷修复分布',
      titleEn: 'Defect fixed distribution',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'requirement-release-distribution',
      category: 'requirement',
      creatorId: 'admin',
      description:
        '所选时间区间内完成的需求，按完成日期排列，横坐标为时间，纵坐标为需求创建到完成的交付周期（天）。其中圆点表示一个已交付的需求，折线表示需求交付周期的滚动均值，蓝色阴影区域表示滚动标准差，横虚线表示所选时间区间内，需求交付周期的平均值',
      descriptionEn: 'Defects under the project to be processed, completed, new trends.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912606,
      identifier: 'requirement-release-distribution',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i2/O1CN01RSFh871HML0k5F2PT_!!6000000000743-2-tps-1068-576.png',
      reportCategorys: 'project,team,sprint,single_project,',
      title: '需求交付分布',
      titleEn: 'Sprint burn down',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'sprint-burn-down',
      category: 'sprint',
      creatorId: 'admin',
      description: '从迭代计划开始到计划结束时间区间内，理想情况下的存量工作项曲线和实际未完成的工作项曲线',
      descriptionEn: 'Defects under the project to be processed, completed, new trends.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912598,
      identifier: 'sprint-burn-down',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i1/O1CN01gw3fxL1MWTpegc94D_!!6000000001442-2-tps-1068-576.png',
      reportCategorys: 'project,sprint,',
      title: '迭代燃尽图',
      titleEn: 'Sprint burn down',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'workitem-trend',
      category: 'defect',
      config: '{"types":2,"timeMode":"day"}',
      creatorId: 'admin',
      description: '所选时间区间内每日新增、修复以及存量(即尚未完成)缺陷的数量曲线',
      descriptionEn: 'Defects under the project to be processed, completed, new trends.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912590,
      identifier: 'defect-progress',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i2/O1CN01WWmxP922UqJ4CKLTW_!!6000000007124-2-tps-1068-576.png',
      reportCategorys: 'project,personal,sprint,single_project,',
      title: '缺陷趋势',
      titleEn: 'Defect progress',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'workitem-trend',
      category: 'requirement',
      config: '{"types":1,"timeMode":"day"}',
      creatorId: 'admin',
      description: '所选时间区间内每日新增、完成以及存量(即尚未完成)需求的数量曲线',
      descriptionEn: 'Needs under the project to be processed, completed, new trends.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912582,
      identifier: 'requirement-progress',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i3/O1CN01mlDJjy1LoyETj1e1q_!!6000000001347-2-tps-1068-576.png',
      reportCategorys: 'project,personal,sprint,single_project,',
      title: '需求趋势',
      titleEn: 'Req progress',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'defect-summary',
      category: 'defect',
      config:
        '{"tableColumnConfigs":[{"name":"名称","nameI18n":"subject","path":"/subject","style":"workitem-title","link":"/url","type":"/type"},{"name":"状态","nameI18n":"status","path":"/stage, /status","style":"color-background-text"},{"name":"优先级","nameI18n":"priority","path":"/priority","style":"color-circle-text","sortKey":"priority"},{"name":"负责人","nameI18n":"assignedToName","path":"/assignedToName, /assignedToAvatarUrl","style":"avatar"},{"name":"项目名","nameI18n":"projectName","path":"/projectName","style":"text"},{"name":"创建时间","nameI18n":"gmtCreate","path":"/gmtCreate","style":"date","format":"YYYY.MM.DD","sortKey":"gmtCreate"},{"name":"计划完成时间","path":"/expectedWorkTime","style":"date","format":"YYYY.MM.DD","sortKey":"expectedWorkTime"},{"name":"逾期时长","path":"/dueDuration","style":"color-time-text","sortKey":"dueDuration"},{"name":"再次打开次数","path":"/reopenNum","color":"text","sortKey":"reopenNum"}]}',
      creatorId: 'admin',
      description: '当前时刻尚未完成、已在修复中、已超过计划完成时间，和未完成且被再次打开过的缺陷数量，可下钻查看列表',
      descriptionEn: 'The overview metrics include amount of project.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912573,
      identifier: 'defect-summary',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i1/O1CN01tz1Nzn1yOeSlj5fha_!!6000000006569-2-tps-1068-576.png',
      reportCategorys: 'project,sprint,single_project,',
      title: '缺陷现状概览',
      titleEn: 'Defect Overview',
      type: 'normal',
      width: 50,
    },
    {
      cardId: 'requirement-summary',
      category: 'requirement',
      config:
        '{"tableColumnConfigs":[{"name":"名称","nameI18n":"subject","path":"/subject","style":"workitem-title","link":"/url","type":"/type"},{"name":"状态","nameI18n":"status","path":"/stage, /status","style":"color-background-text"},{"name":"优先级","nameI18n":"priority","path":"/priority","style":"color-circle-text","sortKey":"priority"},{"name":"负责人","nameI18n":"assignedToName","path":"/assignedToName, /assignedToAvatarUrl","style":"avatar"},{"name":"项目名","nameI18n":"projectName","path":"/projectName","style":"text"},{"name":"创建时间","nameI18n":"gmtCreate","path":"/gmtCreate","style":"date","format":"YYYY.MM.DD","sortKey":"gmtCreate"},{"name":"计划完成时间","nameI18n":"expectedWorkTime","path":"/expectedWorkTime","style":"date","format":"YYYY.MM.DD","sortKey":"expectedWorkTime"},{"name":"逾期时长","nameI18n":"dueDuration","path":"/dueDuration","style":"color-time-text","sortKey":"dueDuration"}]}',
      creatorId: 'admin',
      description: '当前时刻尚未开始、正在进行中，和已超过计划完成时间的需求数量，可下钻查看列表',
      descriptionEn: 'The overview metrics include amount of project.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912564,
      identifier: 'requirement-summary',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i1/O1CN0156jDyH1CqxNsNPpev_!!6000000000133-2-tps-1068-576.png',
      reportCategorys: 'project,sprint,single_project,',
      title: '需求现状概览',
      titleEn: 'Req Overview',
      type: 'normal',
      width: 50,
    },
  ],
}

export const report = {
  code: 200,
  msg: 'ok',
  data: [
    {
      cardId: 'project-worktime-count-rank',
      category: 'project',
      creatorId: 'admin',
      description: '当前时刻各项目预计工时总量的Top5数值，点击"查看全部"可查看完整排名',
      descriptionEn: 'Project workitime count rank.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804913023,
      identifier: 'project-worktime-count-rank',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i2/O1CN01ACgl411rGDuR38xrW_!!6000000005603-2-tps-1068-576.png',
      reportCategorys: 'team,project,',
      title: '预估工时按项目排名',
      titleEn: 'Project workitem count rank',
      type: 'normal',
      width: 50,
      x: 0,
      y: 0,
      w: 6,
      h: 2,
      i: 0,
      active: true,
      moved: false,
    },
    {
      cardId: 'sprint-work-time-investment-rank',
      category: 'sprint',
      creatorId: 'admin',
      description: '所选时间区间内各成员的登记工时Top5数值，点击"查看全部"可查看完整排名',
      descriptionEn: 'Work time investment rank.',
      gmtCreate: 1616060562800,
      gmtModified: 1655804913016,
      identifier: 'sprint-work-time-investment-rank',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i2/O1CN01WdqqQh1GreUoztAKY_!!6000000000676-2-tps-1068-576.png',
      reportCategorys: 'sprint,',
      title: '迭代工时排名',
      titleEn: 'Work time investment rank',
      type: 'normal',
      width: 50,
      x: 6,
      y: 0,
      w: 6,
      h: 2,
      i: 1,
      active: true,
      moved: false,
    },
    {
      cardId: 'team-workitem-done-rank',
      category: 'team',
      creatorId: 'admin',
      description: '当前时刻，指派给各成员的已完成和总的工作项数量。',
      descriptionEn: 'Team workitem done rank',
      gmtCreate: 1616060562800,
      gmtModified: 1655804913008,
      identifier: 'team-workitem-done-rank',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i1/O1CN01Is5XoW1O054uXZkDy_!!6000000001642-2-tps-1068-576.png',
      reportCategorys: 'personal,team,project,sprint,single_project,',
      title: '工作项排名',
      titleEn: 'Team workitem done rank',
      type: 'normal',
      width: 50,
      x: 0,
      y: 2,
      w: 12,
      h: 2,
      i: 2,
      active: true,
      moved: false,
    },
    {
      cardId: 'work-time-burn-down',
      category: 'work_time',
      creatorId: 'admin',
      description: '从迭代计划开始到计划结束时间区间内，理想情况下的每日工时余量曲线和实际的工时余量曲线。',
      descriptionEn: 'Work time burn down',
      gmtCreate: 1616060562800,
      gmtModified: 1655804913001,
      identifier: 'work-time-burn-down',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i4/O1CN012tuwt81JkjLDgJfEC_!!6000000001067-2-tps-1068-576.png',
      reportCategorys: 'sprint,',
      title: '工时燃尽图',
      titleEn: 'Work time burn down',
      type: 'normal',
      width: 50,
      active: true,
      x: 0,
      y: 4,
      w: 6,
      h: 2,
      i: 3,
      moved: false,
    },
    {
      cardId: 'sprint-work-time-summary',
      category: 'sprint',
      creatorId: 'admin',
      description: '当前时刻迭代的工时容量、预估工时、登记工时及到当前时刻预估使用工时与实际登记工时的偏差量。',
      descriptionEn: 'Sprint work time summary',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912993,
      identifier: 'sprint-work-time-summary',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i1/O1CN01f47EcM1icMUkRr55B_!!6000000004433-2-tps-1068-576.png',
      reportCategorys: 'sprint,',
      title: '迭代工时概览',
      titleEn: 'Sprint work time summary',
      type: 'normal',
      width: 50,
      active: true,
      x: 6,
      y: 4,
      w: 6,
      h: 1,
      i: 4,
      moved: false,
    },
    {
      cardId: 'project-workitem-done-count',
      category: 'sprint',
      creatorId: 'admin',
      description: '当前时刻迭代包含的工作项数量和完成情况。',
      descriptionEn: 'Project workitem done count',
      gmtCreate: 1616060562800,
      gmtModified: 1655804912986,
      identifier: 'project-workitem-done-count',
      minWidth: 50,
      modifierId: 'admin',
      organizationId: '0',
      picUrl: 'https://img.alicdn.com/imgextra/i1/O1CN01Q7DVOE1L9kanze9zv_!!6000000001257-2-tps-1068-576.png',
      reportCategorys: 'sprint,',
      title: '迭代工作项概览',
      titleEn: 'Project workitem done count',
      type: 'normal',
      width: 50,
      active: true,
      x: 6,
      y: 5,
      w: 6,
      h: 1,
      i: 5,
      moved: false,
    },
  ],
}
